### ISSUE TITLE
Reto resuelto

### ISSUE THREAD

**Issue by luiscib3r** [juandc/3-languages-challenge#1]
Se desarrolló una webapp para el almacenamiento de contactos en una base de datos MongoDB, se contruyó el frontend de la aplicación con React JS y se desarrollaron tres REST API en tres lenguajes de programación: Javascript, Typescript y Python.

Aquí están los links de los repositorios:

[Frontend](https://github.com/correaleyval/mycontacts-frontend)
[API JS](https://github.com/correaleyval/mycontacts-apijs)
[API TS](https://github.com/correaleyval/mycontacts-apits)
[API PY](https://github.com/correaleyval/mycontacts-apipy)

Demo online: [https://mycontacts.soft4cuba.com](https://mycontacts.soft4cuba.com)

**Comment by juandc** [comment]
¡¡¡Suuuuuuuper!!!
